services:
  db:
    image: postgres:16
    container_name: notes_db
    environment:
      POSTGRES_DB: notes_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: minhasenha
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d notes_db"]
      interval: 10s
      timeout: 5s
      retries: 5

  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: notes_api
    depends_on:
      db:
        condition: service_healthy
    environment:
      SPRING_PROFILES_ACTIVE: docker
      SPRING_SECURITY_USER_NAME: user
      SPRING_SECURITY_USER_PASSWORD: 123456
      DB_URL: jdbc:postgresql://db:5432/notes_db
      DB_USER: postgres
      DB_PASSWORD: minhasenha
      SERVER_PORT: 8080
    ports:
      - "8080:8080"

volumes:
  postgres_data:
